# Generated by Django 6.0.2 on 2026-02-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_region_post_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('INDO', 'INDO'), ('PH', 'PH'), ('MM', 'MM'), ('SG', 'SG'), ('MY', 'MY'), ('TH', 'TH'), ('MENA', 'MENA')], max_length=200),
        ),
    ]
